### ISSUE TITLE
No way to change SQLCipher passphrase

### ISSUE THREAD

**Issue by chrisballinger** [yapstudios/YapDatabase#102] opened 2014-07-29 16:01 UTC
I forgot to implement a way to change the SQLCipher passphrase. Or perhaps this is out of scope of Yap and should be done manually via `PRAGMA rekey`?

http://sqlcipher.net/sqlcipher-api/#rekey

**Comment by robbiehanson** [comment] 2015-02-16 23:23
Duplicate of issue #127

**Closed by robbiehanson** 2015-02-16 23:23 UTC
