### ISSUE TITLE
Can't see Swift files in Yap project.

### ISSUE THREAD

**Issue by MythicLionMan** [yapstudios/YapDatabase#524] opened 2020-07-15 22:43 UTC
I can't see YapDatabaseView.swift and YapDatabaseSecondaryIndex.swift in the project. Is this intentional? (Or perhaps I'm not configuring it correctly). 

I'm not 100% sure how we're importing the project, we have another developer who's reconfigured our build architecture. We used to check Yap out into our own repo, but now we're using Carthage to keep it up to date. I did try checking out the Yap repo on master branch on its own and searching the project for files that end in '.swift' its own and the only files I see are YapDatabase.swift and YapDatabaseQuery.swift.

Not having access to these files hides most of the refined for Swift API. Since the base methods are now all marked with NS_REFINED_FOR_SWIFT I have to refer to them using the '__' prefix from swift code. There's also at least one nullability error in the ObjC versions (in YapDatabaseSecondaryIndexTransaction.__enumerateIndexedValues()) so the Swift API would be preferable.

**Comment by robbiehanson** [comment] 2020-07-15 22:55
> now we're using Carthage

Gotcha, that makes sense. I think this issue was resolved via one of the commits in Issue #505. Specifically via commit c0933753.

Can you check to see which version/branch/commit is being used by your project? If it's the latest tagged version (4.0), then this fix won't be included. If so, can you switch to latest commit in master, and see if the issue is resolved?

It looks like it's time to tag another version.

**Comment by MythicLionMan** [comment] 2020-07-15 23:14
I just tried building using the refined APIs on YapDatabaseViewTransaction using that one and it still didn't work.

I checked the diff and that commit adds YapDatabase.swift and YapDatabaseQuery.swift (the two I already had), but not YapDatabaseView.swift and YapDatabaseSecondaryIndex.swift. I wonder if there are other missing swift files buried in the project.

**Comment by robbiehanson** [comment] 2020-07-16 18:28
Can you give that new commit a try?

**Comment by MythicLionMan** [comment] 2020-07-16 19:31
That one fixed it. Thanks!

**Comment by MythicLionMan** [comment] 2020-07-16 23:02
New commit fixes issue.

**Closed** 2020-07-16 23:02 UTC
