### ISSUE TITLE
2.7.3 - Carthage 

### ISSUE THREAD

**Issue by wm-j-ray** [yapstudios/YapDatabase#221] opened 2015-10-09 18:53 UTC
Did carthage support make it into 2.7.3?  I get this using xCode 7.1 GM (AppStore) and Carthage 0.9.3

Thanx

*** Building scheme "YapDatabase" in YapDatabase.xcodeproj
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Check\ Pods\ Manifest.lock /Users/xxxx/Library/Developer/Xcode/DerivedData/YapDatabase-adksnktlitkttkeyyiiaqrdpbyoa/Build/Intermediates/YapDatabase.build/Release-iphonesimulator/YapDatabase.build/Script-D5F989B8BC82BA94C1FA749A.sh
(1 failure)
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Check\ Pods\ Manifest.lock /Users/xxxx/Library/Developer/Xcode/DerivedData/YapDatabase-adksnktlitkttkeyyiiaqrdpbyoa/Build/Intermediates/YapDatabase.build/Release-iphonesimulator/YapDatabase.build/Script-D5F989B8BC82BA94C1FA749A.sh
(1 failure)

**Comment by robbiehanson** [comment] 2015-10-14 22:17
> Did carthage support make it into 2.7.3?

No, it's currently targeted for 2.7.4.

Carthage support is currently being pursued in the "carthage" branch.

**Comment by robbiehanson** [comment] 2015-10-14 22:17
Duplicate of issue #192

**Closed by robbiehanson** 2015-10-14 22:17 UTC
