### ISSUE TITLE
Question: Is it possible to use YapDatabase without Cocoa LumberJack and Pods

### ISSUE THREAD

**Issue by wm-j-ray** [yapstudios/YapDatabase#217] opened 2015-09-26 20:06 UTC
I can manually get around CocoaPods, but what about Lumberjack?  Does it have to be present to build?

Thanx in advance

**Comment by xinwo** [comment] 2015-09-27 13:52
don't cocopods, but import yapdatabase as a submodule, then define YapDatabaseLoggingTechnique to 0 or 1

**Comment by wm-j-ray** [comment] 2015-09-27 14:01
I'll try that. Thanks.

**Comment by wm-j-ray** [comment] 2015-09-27 20:54
Ok, I know Carthage is slated for 2.7.3 but I'm trying to do it 'manually' be looking at the podspec and building the dependencies.  Is this even possible?

I can Carthage build cocoa lumberjack, but what about the Sqllite3, and the FTS and cipher ?
What gets used? Am I wasting my time ?

I really don't want to use cocoa pods

**Comment by robbiehanson** [comment] 2015-09-28 17:36
> what about Lumberjack? Does it have to be present to build?

As @xinwo mentioned, if define YapDatabaseLoggingTechnique to 0 or 1 (YapDatabaseLoggingTechnique_Disabled or YapDatabaseLoggingTechnique_NSLog). For more information, see YapDatabaseLogging.h.

Basically, within the library, all log statements are defined as YDBLogX(), where 'X' is the log level. These are all macros, and get compiled into:
- Lumberjack log statements
- NSLog statements
- or nothing (compiled out)

depending on the value of 'YapDatabaseLoggingTechnique'.

So if your project defines 'YapDatabaseLoggingTechnique' to 0 or 1, then Lumberjack is no longer a requirement.

> what about the Sqllite3

You need only add sqlite3 to your list of linked binaries.
In Xcode: "Build Phases" -> "Link binary with libraries" -> "libsqlite3.dylib"

> FTS

FullTextSearch is included within libsqlite3.dylib (it's a part of sqlite)

> cipher

If you wish to use SQLCipher, then don't link libsqlite3. IIRC, you need to instead link against the sqlite cipher library. And also define SQLITE_HAS_CODEC.  The SQLCipher should have good documentation on this.

**Comment by robbiehanson** [comment] 2015-09-28 17:42
Closing as a duplicate of issue #192 

Let me know if you have any other questions.

**Closed by robbiehanson** 2015-09-28 17:42 UTC

**Comment by wm-j-ray** [comment] 2015-10-05 17:46
I still can't get this to build without Cocoapods.  I've sourced in YapDatabase, linked in CocoaLumberjack and libsqlite3 but sill get a CocoaLumberjack.h not found error in a Swift Project.

I probably should move on and wait until Yap supports Carthage as I'm not smart enough to even run the hello world example in Swift.
