### ISSUE TITLE
Touching an object does not work as expected

### ISSUE THREAD

**Issue by tommylitang** [yapstudios/YapDatabase#205] opened 2015-08-24 10:45 UTC
In my case, I'm using a view with table view on a list of collections. What I need to do is to invalidate object such that the view could re-evaluate the object with its grouping block and thus update the view. I have tried the following two approaches:
```objc
[transaction touchObjectForKey:userId inCollection:NSStringFromClass([TNTLContact class])];
```
```objc
id object = [transaction objectForKey:key inCollection:@"collection"];
[transaction setObject:object forKey:key inCollection:@"collection"];
```
Based on the documentation, I suppose the above two should work the same. Sadly, only the ```setObject``` approach works for me. I would like to ask if this is expected behaviour or possibly I'm doing wrong.

**Comment by chrisballinger** [comment] 2015-08-24 16:10
Is the object in memory not the same as the object in the database? That
could explain why saving it works and touch doesn't

**Comment by robbiehanson** [comment] 2015-08-24 16:25
Touching the object should work as you expect it to. If not, it could be a bug.

If you invoke:
```objective-c
[transaction touchObjectForKey:userId inCollection:NSStringFromClass([TNTLContact class])];
```
Then the ```[YapDatabaseReadWriteTransaction touchObjectForKey:inCollection:]``` method will forward the touch event to each registered extension via ```[YapDatabaseExtensionTransaction handleTouchObjectForCollectionKey:withRowid:]```.

To make sure this is occurring, try setting a breakpoint in the following:
- [YapDatabaseReadWriteTransaction touchObjectForKey:inCollection:]
- [YapDatabaseViewTransaction handleTouchObjectForCollectionKey:withRowid:]

You should see it eventually create a YapDatabaseViewRowChange for the touch.

This RowChange will then arrive at your main-thread via the YapDatabaseModifiedNotification.

Let me know what you're seeing.

**Comment by tommylitang** [comment] 2015-08-26 10:17
The implementation of ```[YapDatabaseViewTransaction handleTouchObjectForCollectionKey:withRowid:]``` is basically the same as ```[YapDatabaseViewTransaction touchObjectForKey: inCollection:]```, which in the latter one you specified in the comment: 
> "Touching" an item has very minimal overhead. It doesn't cause the groupingBlock or sortingBlock to be invoked, and it doesn't cause any writes to the database.

I think this is why the view is not responding to the touch event since the change has to be reflected by invoking groupingBlock. Any suggestion how I should handle the kind of logic when the groupingBlock is involving factors that change independent of the objects in the view?

For example:
```objc
[YapDatabaseViewGrouping withObjectBlock:^NSString *(YapDatabaseReadTransaction *transaction, NSString *collection, NSString *key, id object) {
    return [self.userSelectedObjectSet containsObject:object];
}];
```

**Comment by robbiehanson** [comment] 2015-08-26 17:54
> Any suggestion how I should handle the kind of logic when the groupingBlock is involving
> factors that change independent of the objects in the view?

Good question.

In addition to your example, in YDB v2.7, the groupingBlock & sortingBlock have a read-only transaction parameter. Which is explicitly designed to allow users to make decisions based on external factors. I.E. factors that may change independent of the object itself.

So I think you're right: the touch implementation within a YDBView SHOULD invoke the groupingBlock / sortingBlock logic.

**Comment by robbiehanson** [comment] 2015-08-26 21:51
This should be fixed now. Let me know if you have any other problems.

**Comment by tommylitang** [comment] 2015-08-27 10:20
I'm now encountering another issue after applying this fix to my application. Objects that are not included in the parent view of a ```YapDatabaseFilteredView``` is passed to the filtered view to test for filteringBlock. As I assumed that only those objects that appear in the parent view would be handled by the filtered view, I didn't check the type/collection in the filteringBlock. This could lead to exception in the filteringBlock or even in the sortingBlock of the parent view when an update event is triggered.

**Comment by robbiehanson** [comment] 2015-09-09 17:37
> Objects that are not included in the parent view of a YapDatabaseFilteredView [are being]
> passed to the filtered view

This would be a serious bug !

> I assumed only those objects that appear in the parent view would be handled by the filtered view

This is the intended operation.

When is this happening ? On touch ? Any idea how I can reproduce it ?

**Comment by robbiehanson** [comment] 2015-09-21 21:25
Minor update on your original issue:

I've now improved the YapDatabaseViewGrouping & YapDatabaseViewSorting objects. They now accept a "YapDatabaseBlockInvoke" bit-mask.  This allows one to (optionally) be more precise concerning when the block should be invoked. For example, one could specify that the block requires an object parameter, but that the block should not be invoked if the object is simply "touched".

The default options remain as we discussed above though.

Can you give me any more information about the second issue you reported ?

**Comment by tommylitang** [comment] 2015-09-24 03:42
Let me see if the bug is still reproducible.

**Comment by tommylitang** [comment] 2015-09-26 07:11
The bug is still happening. When I insert a new object which is not handled by the parent view, the lastHandledGroup of the parent view is overwritten by the operations inside the hooks triggered by the insertion. As a result, the filtered view will still try to process the object unexpectedly. You can refer to #216.

**Comment by robbiehanson** [comment] 2015-09-28 17:10
> the lastHandledGroup of the parent view is overwritten by the operations inside
> the hooks triggered by the insertion

Thank you !!!!!!!!!

I have an idea of how to fix this. And it's something I've been thinking about adding for some time. So this gives me a really good reason why it's needed.

**Comment by robbiehanson** [comment] 2015-09-28 17:45
Closing as duplicate of issue #216

**Closed by robbiehanson** 2015-09-28 17:45 UTC
