### ISSUE TITLE
SQLCipher not working with 2.6.2

### ISSUE THREAD

**Issue by FredericJacobs** [yapstudios/YapDatabase#172] opened 2015-05-12 18:25 UTC
I tried to upgrade YapDatabase to 2.6.2 but in that process, the SQLCipher bindings broke.

**Comment by chrisballinger** [comment] 2015-05-12 18:34
I believe it maybe related to https://github.com/yapstudios/YapDatabase/issues/171

**Comment by robbiehanson** [comment] 2015-05-12 18:36
Yeah, I was worried about #171 . It's so important I think it may be worthy of a 2.6.3 release. Thoughts?

**Comment by chrisballinger** [comment] 2015-05-12 18:44
Hmmm probably, considering that https://github.com/yapstudios/YapDatabase/commit/49ff0ad229a1676cde93790bc5b5df4876f68941 combined with #171 could potentially result in unintentionally unencrypted databases for fresh installs. Would it make sense to at least log a warning if you're using SQLCipher but haven't properly set up the cipherKeyBlock?

**Comment by robbiehanson** [comment] 2015-05-12 18:47
> Would it make sense to at least log a warning if you're using SQLCipher but haven't properly set up the cipherKeyBlock?

I received feedback on this from users. People saying they're using YapDatabase for several different databases within their app. Some encrypted, some not. So if we added this warning, they'd see it every time (for the un-encrypted databases).

**Comment by robbiehanson** [comment] 2015-05-12 18:50
@chrisballinger By the way, any ideas on this: 5e6d7b263037b8a4ab258aae94e4f8c4733fd375 ?

**Comment by chrisballinger** [comment] 2015-05-12 19:05
Oh, part of the problem for the original issue may also be that the SQLCipher xcconfig is being overwritten? https://github.com/yapstudios/YapDatabase/commit/5e6d7b263037b8a4ab258aae94e4f8c4733fd375#diff-91bab37463eca3a5510312918a32501aR52 

As far as the sqlite linter errors, it might be caused by a bug in Cocoapods? Might be worth reporting upstream as a regression?

**Comment by FredericJacobs** [comment] 2015-05-12 19:13
The xcconfig overwrite is probably the issue I encountered.

**Comment by chrisballinger** [comment] 2015-05-12 19:20
Hmm yeah I can't get 2.6.1 to lint properly on 0.37.1, which is frustrating because it seems to work fine when actually integrated into an application. 0.36.x didn't have this issue to my knowledge.

I'll futz around with it and see if I can come up with a fix.

**Comment by chrisballinger** [comment] 2015-05-12 20:32
@robbiehanson This seems to be intended behavior as far as the linter issues, but the 2.6.3 subspec is still broken for SQLCipher because of the empty xcconfig line. Guess we can't have subspec inheritance anymore.

Unfortunately there's no way to replace an existing podspec so to fix it you'll need to push 2.6.4 even though the source is identical to 2.6.3. :-\

```ruby
Pod::Spec.new do |s|
  s.name         = "YapDatabase"
  s.version      = "2.6.4"
  s.summary      = "A key/value store built atop sqlite for iOS & Mac."
  s.homepage     = "https://github.com/yapstudios/YapDatabase"
  s.license      = 'MIT'
  s.ios.deployment_target = '6.0'
  s.osx.deployment_target = '10.8'
  s.author       = { "Robbie Hanson" => "robbiehanson@deusty.com" }
  s.source       = { :git => "https://github.com/yapstudios/YapDatabase.git", :tag => s.version.to_s }

  s.default_subspec = 'standard'

  # use a builtin version of sqlite3
  s.subspec 'standard' do |ss|
    ss.library = 'sqlite3'    
    ss.dependency 'CocoaLumberjack', '~> 1'
    ss.source_files = 'YapDatabase/**/*.{h,m,mm}'
    ss.private_header_files = 'YapDatabase/**/Internal/*.h'
    ss.xcconfig = { 'OTHER_LDFLAGS' => '-weak_library /usr/lib/libc++.dylib' }
    ss.requires_arc = true
  end

  # use SQLCipher and enable -DSQLITE_HAS_CODEC flag
  s.subspec 'SQLCipher' do |ss|
    ss.dependency 'SQLCipher/fts'    
    ss.dependency 'CocoaLumberjack', '~> 1'
    ss.source_files = 'YapDatabase/**/*.{h,m,mm}'
    ss.private_header_files = 'YapDatabase/**/Internal/*.h'
    ss.xcconfig = { 'OTHER_LDFLAGS' => '-weak_library /usr/lib/libc++.dylib', 'OTHER_CFLAGS' => '$(inherited) -DSQLITE_HAS_CODEC' }
    ss.requires_arc = true    
  end
end
```

**Comment by robbiehanson** [comment] 2015-05-12 22:11
> Guess we can't have subspec inheritance anymore

That's what I was guessing. Too bad.

**Comment by robbiehanson** [comment] 2015-05-14 02:01
The podspec should be fixed. And I pushed podspec for v2.6.4

**Closed by robbiehanson** 2015-05-14 02:01 UTC
