### ISSUE TITLE
Can I use YapDatabase without Cocoapods in Swift?

### ISSUE THREAD

**Issue by Goles** [yapstudios/YapDatabase#152] opened 2015-03-26 04:26 UTC
Hey,

I was reading [this question](https://github.com/yapstudios/YapDatabase/issues/85) about setting up YapDatabase with Swift but noticed that it uses Cocoapods. 

* Is there a simple way to add YapDatabase to my project without using Cocoapods at all?
* You guys planning to support something lighter like [Carthage](https://github.com/Carthage/Carthage)?

Cheers!

**Comment by robbiehanson** [comment] 2015-03-26 18:50
> Is there a simple way to add YapDatabase to my project without using Cocoapods at all?

The simplest way I suppose would be to just clone the repo, and then copy the folder into your project/repo. And, of course, add the proper folder(s) within your Xcode project.

> You guys planning to support something lighter like Carthage?

I wouldn't be opposed to this in any way. Skimming the Carthage page, looks like should first get a framework target build for YapDatabase going.

**Comment by Goles** [comment] 2015-03-26 20:17
@robbiehanson Thanks for your reply :)

About carthage, yes, I guess an iOS 8+ Framework target is necessary :+1:

**Comment by danthorpe** [comment] 2015-04-07 13:41
Just to leave my own feedback/experience here as it might be useful. Before Cocoapods 0.36 (with support for frameworks) I was sub-moduling YapDB (and its dependencies) and then creating my own framework for it, although you can also just add it to an existing module to get started. You'll just need to sort out the access levels on the headers in your bridging file.

Since Cocoapods 0.36, YapDB works fine as a framework out of the box.

**Comment by robbiehanson** [comment] 2015-05-14 00:22
Duplicate of issue #132

**Closed by robbiehanson** 2015-05-14 00:22 UTC
