### ISSUE TITLE
Auto-complete in 2.6.4 is broken

### ISSUE THREAD

**Issue by darrensi** [yapstudios/YapDatabase#173] opened 2015-05-14 20:04 UTC
Parameter names are missing when auto-completing e.g.

```[transaction enumerateKeysAndObjectsInCollection:@"collection" usingBlock:^(NSString * __nonnull, id __nonnull, BOOL * __nonnull) {
}];```

**Comment by corristo** [comment] 2015-05-14 20:54
Looks like Xcode bug caused by nullability annotations.

**Comment by chrisballinger** [comment] 2015-05-14 23:33
Looks like Apple is aware because they said it was a duplicate of rdar://20755276

https://openradar.appspot.com/20723086
https://openradar.appspot.com/20835509

**Comment by darrensi** [comment] 2015-05-15 15:32
That's a pain. 
It also affects the inline help so the only way to get the parameter names is to look at the header files.
Anyone know which version was the last one that worked?

**Comment by aaresta** [comment] 2015-05-21 13:29
2.6.1 is working fine here

**Comment by StormXX** [comment] 2015-08-04 09:19
now it is 2.6.5, and I meet this problem too..how to fix it????

**Comment by corristo** [comment] 2015-08-04 09:21
@StormXX it's an Xcode bug, unfortunately.

**Comment by chrisballinger** [comment] 2015-08-04 18:44
It's fixed in Xcode 7

**Comment by robbiehanson** [comment] 2015-10-09 21:05
Closing this issue because:

- it was a bug in Xcode
- the bug is fixed in Xcode v7
- Xcode v7 is now officially released

**Closed by robbiehanson** 2015-10-09 21:05 UTC

**Comment by malhal** [comment] 2016-02-07 17:52
Bug is back in Xcode 7.2.1
