### ISSUE TITLE
CloudCore

### ISSUE THREAD

**Issue by dezinezync** [yapstudios/YapDatabase#427] opened 2017-11-04 13:53 UTC
Hi, I was looking into implementing CloudCore in one of our existing projects that is already built on top of YapDatabase. I read through it's wiki page and got it implemented somewhat. 

I am running into two issues.
1. When building the iOS Framework via `carthage`, the CloudCore files are not included. I'm on the `master` branch. Is this intentional at the moment since it's still "beta" of sorts? 
2. I manually added the CloudCore files to the project and rebuilt it so I can implement it in my Project. However, when I try to register the extension with the database, I get `NO` via the sync method and `ready=NO` when using the async method. Is this also intentional at the moment? 

If you believe what I'm trying should work, do let me know so I can share my code if required. I tried registering the CloudKit extension which works via both the async and sync methods so I'm sure it's not those specific APIs which are causing the issue.

**Comment by robbiehanson** [comment] 2017-11-04 16:01
> When building the iOS Framework via carthage, the CloudCore files are not included. [...] Is this intentional [...]?

No. That's a bug. Thank you for pointing this out.

Fixed via commit 0cd8bf6c8ebbe17942327f170010866dc493a513

> when I try to register the extension with the database, I get NO via the sync method and ready=NO when using the async method. Is this also intentional at the moment?

No, it's not intentional. The wiki documentation is in need of much improvement.

You may be running into problems because YDBCloudCore is rejecting the configuration during registration. 

My first guess would be that you haven't registered a pipeline, and YDBCloudCore is objecting to this (because its required). Try setting a breakpoint in `[YapDatabaseCloudCore supportsDatabase:withRegisteredExtensions:]`:

```objective-c
- (BOOL)supportsDatabase:(YapDatabase __unused *)database
withRegisteredExtensions:(NSDictionary __unused *)registeredExtensions
{
	if ([self defaultPipeline] == nil)
	{
		YDBLogError(@"You MUST register a default pipeline BEFORE registering the extension with the database."
		            @" See [YapDatabaseCloudCore registerPipeline:].");
		return NO;
	}
	
	return YES;
}
```

If that's not the case, try setting a breakpoint in `[YapDatabaseCloudCoreTransaction createIfNeeded]`. One of these should be the culprit that's causing the registration to return NO.

**Comment by dezinezync** [comment] 2017-11-04 18:43
Thank you for the prompt update, Robbie. All my further correspondence is based on the commit you've mentioned.

As a sample, here's my code:

```objc
YapDatabaseCloudCoreOptions *options = [YapDatabaseCloudCoreOptions new];
options.enableTagSupport = YES;
    
YapDatabaseCloudCore *cloudCore = [[YapDatabaseCloudCore alloc] initWithVersionTag:@"1" options:options];
    
YapDatabaseCloudCorePipeline *pipeline = [[YapDatabaseCloudCorePipeline alloc] initWithName:YapDatabaseCloudCoreDefaultPipelineName delegate:self];
    
__unused BOOL registered = [cloudCore registerPipeline:pipeline];
    
[self.database asyncRegisterExtension:cloudCore withName:kCloudCoreExtension completionBlock:^(BOOL ready) {
    DDLogDebug(@"Ready %@", @(ready));
}];
```

I was previously registering the pipeline with a custom name but for the sake of debugging, I've since used the `YapDatabaseCloudCoreDefaultPipelineName` key provided by the framework.

In either of the cases, registering the pipeline always returned positive. I setup the two breakpoints you mentioned and neither them were triggered when trying to register the extension. I believe I have made some obvious mistake and haven't realised it yet. 

Some other information:
- I have already implemented a blank implementation of the delegate method: `startOperation:(YapDatabaseCloudCoreOperation *)operation forPipeline:(YapDatabaseCloudCorePipeline *)pipeline` to check if it gets triggered.
- To force a change, I call a method which inserts a new object in the database 4s after the application launches. 

Given that the extension never registers successfully, the method is never called, which is expected. I wanted to be sure that the return value is not a cosmetic bug somewhere in the framework and it indeed isn't.

**Comment by robbiehanson** [comment] 2017-11-04 22:05
I was able to reproduce your issue. Let me know if the ^above^ commit doesn't fix it for you.

Also, feel free to open up other issues for any other problems you may run into. I know the documentation for CloudCore is horribly lacking at the moment.

**Closed by robbiehanson** 2017-11-04 22:05 UTC
